"""index fuel/service date and attachment fk

Revision ID: c1ee3d6690cd
Revises: d92624e10af4
Create Date: 2026-09-27 13:44:51.116839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1ee3d6690cd'
down_revision: Union[str, Sequence[str], None] = 'd92624e10af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attachment_service_entry_id'), 'attachment', ['service_entry_id'], unique=False)
    op.create_index(op.f('ix_fuelentry_date'), 'fuelentry', ['date'], unique=False)
    op.create_index(op.f('ix_serviceentry_date'), 'serviceentry', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serviceentry_date'), table_name='serviceentry')
    op.drop_index(op.f('ix_fuelentry_date'), table_name='fuelentry')
    op.drop_index(op.f('ix_attachment_service_entry_id'), table_name='attachment')
    # ### end Alembic commands ###
