"""add full_tank to fuel entries

Revision ID: d92624e10af4
Revises: 86aacad3c569
Create Date: 2026-09-05 12:13:05.682994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd92624e10af4'
down_revision: Union[str, Sequence[str], None] = '86aacad3c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fuelentry',
        sa.Column('full_tank', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuelentry', 'full_tank')
    # ### end Alembic commands ###
